"""initial schema

Creates every table for the Shero WhatsApp ordering bot: outlets, customers,
conversations, inbound message dedupe log, delivery slots, slot holds and
orders.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-22
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('inbound_messages',
        sa.Column('provider_message_id', sa.String(length=128), nullable=False),
        sa.Column('whatsapp_number', sa.String(length=32), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_inbound_messages_provider_message_id'), 'inbound_messages', ['provider_message_id'], unique=True)
        op.create_index(op.f('ix_inbound_messages_whatsapp_number'), 'inbound_messages', ['whatsapp_number'], unique=False)
        op.create_table('outlets',
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('code', sa.String(length=40), nullable=False),
        sa.Column('address_line1', sa.String(length=255), nullable=False),
        sa.Column('address_line2', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=120), nullable=False),
        sa.Column('state', sa.String(length=80), nullable=False),
        sa.Column('postal_code', sa.String(length=20), nullable=False),
        sa.Column('country', sa.String(length=2), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('delivery_radius_km', sa.Float(), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('kitchen_whatsapp', sa.String(length=32), nullable=True),
        sa.Column('kitchen_email', sa.String(length=255), nullable=True),
        sa.Column('cuisines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('timezone', sa.String(length=64), nullable=False),
        sa.Column('slot_capacity', sa.Integer(), nullable=False),
        sa.Column('slot_length_minutes', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
        op.create_table('customers',
        sa.Column('whatsapp_number', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('address_line1', sa.String(length=255), nullable=True),
        sa.Column('apartment_unit', sa.String(length=120), nullable=True),
        sa.Column('delivery_instructions', sa.String(length=500), nullable=True),
        sa.Column('contact_number', sa.String(length=32), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('cuisine_preference', sa.String(length=60), nullable=True),
        sa.Column('preferred_outlet_id', sa.Uuid(), nullable=True),
        sa.Column('distance_km', sa.Float(), nullable=True),
        sa.Column('lead_source', sa.String(length=80), nullable=False),
        sa.Column('ad_id', sa.String(length=80), nullable=True),
        sa.Column('campaign_id', sa.String(length=80), nullable=True),
        sa.Column('referral_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('zoho_lead_id', sa.String(length=40), nullable=True),
        sa.Column('zoho_contact_id', sa.String(length=40), nullable=True),
        sa.Column('lead_stage', sa.String(length=40), nullable=False),
        sa.Column('stage_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('is_converted', sa.Boolean(), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['preferred_outlet_id'], ['outlets.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_customers_whatsapp_number'), 'customers', ['whatsapp_number'], unique=True)
        op.create_index(op.f('ix_customers_zoho_contact_id'), 'customers', ['zoho_contact_id'], unique=False)
        op.create_index(op.f('ix_customers_zoho_lead_id'), 'customers', ['zoho_lead_id'], unique=False)
        op.create_table('delivery_slots',
        sa.Column('outlet_id', sa.Uuid(), nullable=False),
        sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('reserved_count', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_slot_outlet_start', 'delivery_slots', ['outlet_id', 'starts_at'], unique=False)
        op.create_table('conversations',
        sa.Column('customer_id', sa.Uuid(), nullable=False),
        sa.Column('step', sa.String(length=48), nullable=False),
        sa.Column('previous_step', sa.String(length=48), nullable=True),
        sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('customer_id', name='uq_conversation_customer')
        )
        op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
        op.create_table('orders',
        sa.Column('order_number', sa.String(length=24), nullable=False),
        sa.Column('customer_id', sa.Uuid(), nullable=False),
        sa.Column('outlet_id', sa.Uuid(), nullable=True),
        sa.Column('slot_id', sa.Uuid(), nullable=True),
        sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('dish_total', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('extra_fees', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('delivery_address', sa.String(length=255), nullable=True),
        sa.Column('apartment_unit', sa.String(length=120), nullable=True),
        sa.Column('delivery_instructions', sa.String(length=500), nullable=True),
        sa.Column('contact_number', sa.String(length=32), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('delivery_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column('delivery_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('slot_starts_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('slot_ends_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('slot_label', sa.String(length=80), nullable=True),
        sa.Column('payment_status', sa.String(length=20), nullable=False),
        sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_refund_id', sa.String(length=255), nullable=True),
        sa.Column('checkout_url', sa.Text(), nullable=True),
        sa.Column('payment_link_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('stage', sa.String(length=32), nullable=False),
        sa.Column('stage_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('sent_to_kitchen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('out_for_delivery_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('zoho_order_id', sa.String(length=40), nullable=True),
        sa.Column('uber_quote_id', sa.String(length=128), nullable=True),
        sa.Column('uber_quote_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('feedback_rating', sa.String(length=20), nullable=True),
        sa.Column('feedback_requested_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('feedback_received_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('item_count', sa.Integer(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['slot_id'], ['delivery_slots.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
        op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
        op.create_index(op.f('ix_orders_outlet_id'), 'orders', ['outlet_id'], unique=False)
        op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
        op.create_index(op.f('ix_orders_stage'), 'orders', ['stage'], unique=False)
        op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=False)
        op.create_index(op.f('ix_orders_stripe_session_id'), 'orders', ['stripe_session_id'], unique=False)
        op.create_index(op.f('ix_orders_zoho_order_id'), 'orders', ['zoho_order_id'], unique=False)
        op.create_table('slot_holds',
        sa.Column('slot_id', sa.Uuid(), nullable=False),
        sa.Column('order_id', sa.Uuid(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['slot_id'], ['delivery_slots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_slot_holds_order_id'), 'slot_holds', ['order_id'], unique=False)
        op.create_index(op.f('ix_slot_holds_slot_id'), 'slot_holds', ['slot_id'], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index(op.f('ix_slot_holds_slot_id'), table_name='slot_holds')
        op.drop_index(op.f('ix_slot_holds_order_id'), table_name='slot_holds')
        op.drop_table('slot_holds')
        op.drop_index(op.f('ix_orders_zoho_order_id'), table_name='orders')
        op.drop_index(op.f('ix_orders_stripe_session_id'), table_name='orders')
        op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
        op.drop_index(op.f('ix_orders_stage'), table_name='orders')
        op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
        op.drop_index(op.f('ix_orders_outlet_id'), table_name='orders')
        op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
        op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
        op.drop_table('orders')
        op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
        op.drop_table('conversations')
        op.drop_index('ix_slot_outlet_start', table_name='delivery_slots')
        op.drop_table('delivery_slots')
        op.drop_index(op.f('ix_customers_zoho_lead_id'), table_name='customers')
        op.drop_index(op.f('ix_customers_zoho_contact_id'), table_name='customers')
        op.drop_index(op.f('ix_customers_whatsapp_number'), table_name='customers')
        op.drop_table('customers')
        op.drop_table('outlets')
        op.drop_index(op.f('ix_inbound_messages_whatsapp_number'), table_name='inbound_messages')
        op.drop_index(op.f('ix_inbound_messages_provider_message_id'), table_name='inbound_messages')
        op.drop_table('inbound_messages')
        # ### end Alembic commands ###
