"""menu, admin settings and single-kitchen service area

Adds the tables behind the admin dashboard:

  * cuisines / categories / menu_items - the menu imported from the client's
    Google Sheet, replacing the Meta catalogue as the source of truth
  * app_settings - credentials editable from the Settings page
  * admin_users - dashboard logins

Also extends outlets with a service area (radius, ZIP list, or both) and an
is_primary flag, for the single-kitchen model.

Revision ID: 0002_menu_and_admin
Revises: 0001_initial
Create Date: 2026-09-23
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_menu_and_admin"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Note: the three outlets columns carry a server_default so the ALTER
    # succeeds on a table that already holds rows. The ORM supplies its own
    # defaults for new records.
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('admin_users',
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=True),
        sa.Column('password_hash', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
        op.create_table('app_settings',
        sa.Column('key', sa.String(length=80), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('is_secret', sa.Boolean(), nullable=False),
        sa.Column('updated_by', sa.String(length=120), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
        op.create_table('cuisines',
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('slug', sa.String(length=80), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index(op.f('ix_cuisines_slug'), 'cuisines', ['slug'], unique=True)
        op.create_table('categories',
        sa.Column('cuisine_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cuisine_id', 'slug', name='uq_category_cuisine_slug')
        )
        op.create_index(op.f('ix_categories_cuisine_id'), 'categories', ['cuisine_id'], unique=False)
        op.create_table('menu_items',
        sa.Column('category_id', sa.Uuid(), nullable=False),
        sa.Column('retailer_id', sa.String(length=120), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('pack_size', sa.String(length=80), nullable=True),
        sa.Column('serves', sa.String(length=80), nullable=True),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('is_available', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_menu_item_category_position', 'menu_items', ['category_id', 'position'], unique=False)
        op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
        op.create_index(op.f('ix_menu_items_retailer_id'), 'menu_items', ['retailer_id'], unique=True)
        op.add_column('outlets', sa.Column('service_area_mode', sa.String(length=10),
              nullable=False, server_default='radius'))
        op.add_column('outlets', sa.Column('service_zips', postgresql.JSONB(astext_type=sa.Text()),
              nullable=False, server_default='[]'))
        op.add_column('outlets', sa.Column('is_primary', sa.Boolean(),
              nullable=False, server_default=sa.false()))
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('outlets', 'is_primary')
        op.drop_column('outlets', 'service_zips')
        op.drop_column('outlets', 'service_area_mode')
        op.drop_index(op.f('ix_menu_items_retailer_id'), table_name='menu_items')
        op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
        op.drop_index('ix_menu_item_category_position', table_name='menu_items')
        op.drop_table('menu_items')
        op.drop_index(op.f('ix_categories_cuisine_id'), table_name='categories')
        op.drop_table('categories')
        op.drop_index(op.f('ix_cuisines_slug'), table_name='cuisines')
        op.drop_table('cuisines')
        op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
        op.drop_table('app_settings')
        op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
        op.drop_table('admin_users')
        # ### end Alembic commands ###
